from xquces.agp import (
    AGPStateParameterization,
    agp_amplitudes_from_eta,
    agp_amplitudes_from_parameters,
    agp_amplitudes_jacobian_from_parameters,
    agp_eta_from_amplitudes,
    agp_eta_from_parameters,
    agp_eta_jacobian_from_parameters,
    agp_parameters_from_amplitudes,
    agp_parameters_from_eta,
    agp_state,
    agp_state_jacobian,
)
from xquces.pair_uccd import (
    PairUCCDStateParameterization,
    apply_pair_uccd_reference_global,
    pair_uccd_generator_from_parameters,
    pair_uccd_state,
    pair_uccd_state_jacobian,
    pair_uccd_unitary_from_parameters,
)
from xquces.states import (
    apply_doci_unitary,
    determinant_index,
    determinant_state,
    doci_amplitudes_from_parameters,
    doci_amplitudes_from_state,
    doci_amplitudes_jacobian_from_parameters,
    doci_dimension,
    doci_params_from_state,
    doci_parameters_from_amplitudes,
    doci_state,
    doci_state_jacobian,
    hartree_fock_state,
    linear_combination_state,
    open_shell_singlet_state,
)
from xquces.state_parameterization import (
    CompositeReferenceAnsatzParameterization,
    DOCIStateParameterization,
    make_composite_reference_ansatz_jacobian,
)
from xquces.hamiltonians import MolecularHamiltonianLinearOperator
from xquces.sqd import run_sqd_from_statevector
from xquces.gcr import (
    GCR2DOCIReferenceParameterization,
    GCR2NOCIReferenceParameterization,
    GCR2PairUCCDParameterization,
    GCR2SpectatorOrbitalParameterization,
    GCR3PairUCCDParameterization,
    GCR4PairUCCDParameterization,
    GCRAnsatz,
    GCRSpinBalancedParameterization,
    GCRSpinRestrictedParameterization,
    IGCR23Ansatz,
    IGCR23SpinRestrictedParameterization,
    IGCR234Ansatz,
    IGCR234SpinRestrictedParameterization,
    gcr_from_ucj_ansatz,
)
from xquces.gcr.init import GaugeFixedGCRBalancedDFSeed
from xquces.ucj._unitary import (
    AntiHermitianUnitaryChart,
    antihermitian_from_parameters,
    parameters_from_antihermitian,
    parameters_from_unitary,
    unitary_from_parameters,
)
from xquces.ucj.init import (
    UCJBalancedDFSeed,
    UCJRestrictedHeuristicSeed,
    UCJRestrictedProjectedDFSeed,
    heuristic_restricted_pair_params_from_t2,
    project_spin_balanced_to_spin_restricted,
)
from xquces.ucj.model import SpinBalancedSpec, SpinRestrictedSpec, UCJAnsatz, UCJLayer
from xquces.ucj.parameterization import (
    GaugeFixedUCJSpinBalancedParameterization,
    UCJSpinBalancedParameterization,
    UCJSpinRestrictedParameterization,
)
from xquces.optimize.linear_method import minimize_linear_method
from xquces.gcr.igcr2 import IGCR2SpinRestrictedParameterization
from xquces.gcr.igcr3 import IGCR3SpinRestrictedParameterization
from xquces.gcr.igcr4 import IGCR4SpinRestrictedParameterization
from xquces.utils import apply_spin_square, spin_square

__all__ = [
    "hartree_fock_state",
    "doci_state",
    "doci_dimension",
    "doci_amplitudes_from_parameters",
    "doci_amplitudes_jacobian_from_parameters",
    "doci_parameters_from_amplitudes",
    "doci_amplitudes_from_state",
    "doci_params_from_state",
    "doci_state_jacobian",
    "apply_doci_unitary",
    "agp_state",
    "agp_state_jacobian",
    "agp_eta_from_parameters",
    "agp_eta_jacobian_from_parameters",
    "agp_parameters_from_eta",
    "agp_amplitudes_from_eta",
    "agp_amplitudes_from_parameters",
    "agp_amplitudes_jacobian_from_parameters",
    "agp_eta_from_amplitudes",
    "agp_parameters_from_amplitudes",
    "pair_uccd_generator_from_parameters",
    "pair_uccd_unitary_from_parameters",
    "apply_pair_uccd_reference_global",
    "pair_uccd_state",
    "pair_uccd_state_jacobian",
    "determinant_index",
    "determinant_state",
    "linear_combination_state",
    "open_shell_singlet_state",
    "DOCIStateParameterization",
    "AGPStateParameterization",
    "PairUCCDStateParameterization",
    "CompositeReferenceAnsatzParameterization",
    "make_composite_reference_ansatz_jacobian",
    "MolecularHamiltonianLinearOperator",
    "run_sqd_from_statevector",
    "GCRAnsatz",
    "GCRSpinBalancedParameterization",
    "GCRSpinRestrictedParameterization",
    "GCR2DOCIReferenceParameterization",
    "GCR2NOCIReferenceParameterization",
    "GCR2PairUCCDParameterization",
    "GCR3PairUCCDParameterization",
    "GCR4PairUCCDParameterization",
    "GCR2SpectatorOrbitalParameterization",
    "gcr_from_ucj_ansatz",
    "AntiHermitianUnitaryChart",
    "antihermitian_from_parameters",
    "parameters_from_antihermitian",
    "parameters_from_unitary",
    "unitary_from_parameters",
    "SpinBalancedSpec",
    "SpinRestrictedSpec",
    "UCJLayer",
    "UCJAnsatz",
    "UCJSpinBalancedParameterization",
    "UCJSpinRestrictedParameterization",
    "GaugeFixedUCJSpinBalancedParameterization",
    "UCJBalancedDFSeed",
    "UCJRestrictedHeuristicSeed",
    "UCJRestrictedProjectedDFSeed",
    "heuristic_restricted_pair_params_from_t2",
    "project_spin_balanced_to_spin_restricted",
    "IGCR2SpinRestrictedParameterization",
    "IGCR23Ansatz",
    "IGCR23SpinRestrictedParameterization",
    "IGCR3SpinRestrictedParameterization",
    "IGCR4SpinRestrictedParameterization",
    "IGCR234Ansatz",
    "IGCR234SpinRestrictedParameterization",
    "minimize_linear_method",
    "apply_spin_square",
    "spin_square",
]
