from xquces.agp import (
    AGPStateParameterization,
    agp_amplitudes_from_eta,
    agp_amplitudes_from_parameters,
    agp_amplitudes_jacobian_from_parameters,
    agp_eta_from_amplitudes,
    agp_eta_from_parameters,
    agp_eta_jacobian_from_parameters,
    agp_parameters_from_amplitudes,
    agp_parameters_from_eta,
    agp_state,
    agp_state_jacobian,
)

from xquces.gcr.igcr2 import (
    IGCR2Ansatz,
    IGCR2SpinBalancedParameterization,
    IGCR2SpinBalancedSpec,
    IGCR2SpinRestrictedParameterization,
    IGCR2SpinRestrictedSpec,
    exact_reference_ov_params_from_unitary,
    exact_reference_ov_unitary,
    orbital_relabeling_from_overlap,
    reduce_spin_balanced,
    reduce_spin_restricted,
    relabel_igcr2_ansatz_orbitals,
)
from xquces.gates import (
    apply_gcr_spin_balanced,
    apply_gcr_spin_restricted,
    apply_igcr2_spin_restricted,
)

from xquces.gcr.igcr3 import (
    IGCR3Ansatz,
    IGCR3CubicReduction,
    IGCR3SpinRestrictedParameterization,
    IGCR3SpinRestrictedSpec,
    apply_igcr3_spin_restricted_diagonal,
    igcr3_from_igcr2_ansatz,
    relabel_igcr3_ansatz_orbitals,
    spin_restricted_triples_seed_from_pair_params,
)


from xquces.pair_uccd import (
    PairUCCDStateParameterization,
    ProductPairUCCDStateParameterization,
    apply_pair_uccd_reference_global,
    apply_product_pair_uccd_reference_global,
    pair_uccd_generator_from_parameters,
    pair_uccd_parameters_from_t2,
    pair_uccd_state,
    pair_uccd_state_jacobian,
    pair_uccd_unitary_from_parameters,
    product_pair_uccd_state,
    product_pair_uccd_state_jacobian,
    product_pair_uccd_unitary_from_parameters,
)
from xquces.states import (
    apply_doci_unitary,
    determinant_index,
    determinant_state,
    doci_amplitudes_from_parameters,
    doci_amplitudes_from_state,
    doci_amplitudes_jacobian_from_parameters,
    doci_dimension,
    doci_params_from_state,
    doci_parameters_from_amplitudes,
    doci_state,
    doci_state_jacobian,
    hartree_fock_state,
    linear_combination_state,
    open_shell_singlet_state,
)
from xquces.state_parameterization import (
    CompositeReferenceAnsatzParameterization,
    DOCIStateParameterization,
    FixedReferenceAnsatzParameterization,
    apply_ansatz_parameterization,
    make_composite_reference_ansatz_jacobian,
)
from xquces.hamiltonians import MolecularHamiltonianLinearOperator
from xquces.sqd import run_sqd_from_statevector
from xquces.gcr import (
    GCR2DOCIReferenceParameterization,
    GCR2NOCIReferenceParameterization,
    GCR2PairUCCDParameterization,
    GCR2ProductPairUCCDParameterization,
    GCR2SpectatorOrbitalParameterization,
    GCR3PairUCCDParameterization,
    GCR3ProductPairUCCDParameterization,
    GCR4PairUCCDParameterization,
    GCR4ProductPairUCCDParameterization,
    GCRPairUCCDParameterization,
    GCRAnsatz,
    GCRSpinBalancedParameterization,
    GCRSpinRestrictedParameterization,
    HigherOrderLiftSeed,
    IGCR23Ansatz,
    IGCR23SpinRestrictedParameterization,
    IGCR234Ansatz,
    IGCR234SpinRestrictedParameterization,
    IGCR4PairSpinAnsatz,
    IGCR4PairSpinParameterization,
    IGCR4PairSpinSpec,
    IGCRSpinRestrictedParameterization,
    default_adjacent_spin_pairs,
    gcr_from_ucj_ansatz,
)
from xquces.gcr.init import GaugeFixedGCRBalancedDFSeed
from xquces.ucj._unitary import (
    AntiHermitianUnitaryChart,
    antihermitian_from_parameters,
    parameters_from_antihermitian,
    parameters_from_unitary,
    unitary_from_parameters,
)
from xquces.ucj.init import (
    UCJBalancedDFSeed,
    UCJRestrictedHeuristicSeed,
    UCJRestrictedProjectedDFSeed,
    heuristic_restricted_pair_params_from_t2,
    project_spin_balanced_to_spin_restricted,
)
from xquces.ucj.model import SpinBalancedSpec, SpinRestrictedSpec, UCJAnsatz, UCJLayer
from xquces.ucj.parameterization import (
    GaugeFixedUCJSpinBalancedParameterization,
    UCJSpinBalancedParameterization,
    UCJSpinRestrictedParameterization,
)
from xquces.optimize.linear_method import minimize_linear_method
from xquces.optimize.subspace_linear_method import (
    gradient_coordinate_subspace,
    minimize_subspace_linear_method,
)
from xquces.continuation import (
    GCR2ForwardOptimizer,
    GCR2OptimizationResult,
    MolecularContinuationPoint,
    MolecularForwardContinuator,
    OrbitalTracker,
    OrbitalTrackingDiagnostics,
    RCCSDContinuation,
    dense_matrix_from_linear_operator,
    exact_ground_energy,
    make_ffsim_molecular_data,
    projector_shifted_operator,
    track_occ_virt_orbitals,
)
from xquces.gcr.igcr2 import IGCR2SpinRestrictedParameterization
from xquces.gcr.igcr3 import IGCR3SpinRestrictedParameterization
from xquces.gcr.igcr4 import IGCR4SpinRestrictedParameterization
from xquces.utils import apply_spin_square, spin_square, build_hydrogen_ring

__all__ = [
    "hartree_fock_state",
    "doci_state",
    "doci_dimension",
    "doci_amplitudes_from_parameters",
    "doci_amplitudes_jacobian_from_parameters",
    "doci_parameters_from_amplitudes",
    "doci_amplitudes_from_state",
    "doci_params_from_state",
    "doci_state_jacobian",
    "apply_doci_unitary",
    "agp_state",
    "agp_state_jacobian",
    "agp_eta_from_parameters",
    "agp_eta_jacobian_from_parameters",
    "agp_parameters_from_eta",
    "agp_amplitudes_from_eta",
    "agp_amplitudes_from_parameters",
    "agp_amplitudes_jacobian_from_parameters",
    "agp_eta_from_amplitudes",
    "agp_parameters_from_amplitudes",
    "pair_uccd_generator_from_parameters",
    "pair_uccd_parameters_from_t2",
    "pair_uccd_unitary_from_parameters",
    "product_pair_uccd_unitary_from_parameters",
    "apply_pair_uccd_reference_global",
    "apply_product_pair_uccd_reference_global",
    "pair_uccd_state",
    "pair_uccd_state_jacobian",
    "product_pair_uccd_state",
    "product_pair_uccd_state_jacobian",
    "determinant_index",
    "determinant_state",
    "linear_combination_state",
    "open_shell_singlet_state",
    "DOCIStateParameterization",
    "AGPStateParameterization",
    "PairUCCDStateParameterization",
    "ProductPairUCCDStateParameterization",
    "CompositeReferenceAnsatzParameterization",
    "FixedReferenceAnsatzParameterization",
    "apply_ansatz_parameterization",
    "make_composite_reference_ansatz_jacobian",
    "MolecularHamiltonianLinearOperator",
    "run_sqd_from_statevector",
    "GCRAnsatz",
    "GCRSpinBalancedParameterization",
    "GCRSpinRestrictedParameterization",
    "GCR2DOCIReferenceParameterization",
    "GCR2NOCIReferenceParameterization",
    "GCR2PairUCCDParameterization",
    "GCR2ProductPairUCCDParameterization",
    "GCR3PairUCCDParameterization",
    "GCR3ProductPairUCCDParameterization",
    "GCR4PairUCCDParameterization",
    "GCR4ProductPairUCCDParameterization",
    "GCRPairUCCDParameterization",
    "GCR2SpectatorOrbitalParameterization",
    "HigherOrderLiftSeed",
    "gcr_from_ucj_ansatz",
    "AntiHermitianUnitaryChart",
    "antihermitian_from_parameters",
    "parameters_from_antihermitian",
    "parameters_from_unitary",
    "unitary_from_parameters",
    "SpinBalancedSpec",
    "SpinRestrictedSpec",
    "UCJLayer",
    "UCJAnsatz",
    "UCJSpinBalancedParameterization",
    "UCJSpinRestrictedParameterization",
    "GaugeFixedUCJSpinBalancedParameterization",
    "UCJBalancedDFSeed",
    "UCJRestrictedHeuristicSeed",
    "UCJRestrictedProjectedDFSeed",
    "heuristic_restricted_pair_params_from_t2",
    "project_spin_balanced_to_spin_restricted",
    "IGCR2SpinRestrictedParameterization",
    "IGCR23Ansatz",
    "IGCR23SpinRestrictedParameterization",
    "IGCR3SpinRestrictedParameterization",
    "IGCR4SpinRestrictedParameterization",
    "IGCR4PairSpinAnsatz",
    "IGCR4PairSpinParameterization",
    "IGCR4PairSpinSpec",
    "default_adjacent_spin_pairs",
    "IGCR234Ansatz",
    "IGCR234SpinRestrictedParameterization",
    "IGCRSpinRestrictedParameterization",
    "gradient_coordinate_subspace",
    "minimize_linear_method",
    "minimize_subspace_linear_method",
    "GCR2ForwardOptimizer",
    "GCR2OptimizationResult",
    "MolecularContinuationPoint",
    "MolecularForwardContinuator",
    "OrbitalTracker",
    "OrbitalTrackingDiagnostics",
    "RCCSDContinuation",
    "dense_matrix_from_linear_operator",
    "exact_ground_energy",
    "make_ffsim_molecular_data",
    "projector_shifted_operator",
    "track_occ_virt_orbitals",
    "apply_spin_square",
    "spin_square",
]
